export const domains = [
  "SaaS",
  "Fintech",
  "Travel & Booking",
  "E-commerce",
  "Dating & Social",
  "Marketplaces",
  "EdTech",
  "Healthcare",
  "AI Products",
  "Productivity Tools",
  "Creator Platforms",
  "On-Demand Services",
  "Logistics & Delivery",
  "Real Estate",
  "Fitness & Wellness",
  "Media & Content",
  "Dating",
  "Entertainment",
];